services:
  mongodb:
    image: mongo:6.0
    container_name: ai-publisher-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  backend:
    build: ./backend
    container_name: ai-publisher-backend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/ai-publisher
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: ai-publisher-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb-data: